exports                    = exports ? this
fs                         = require 'fs'
path                       = require 'path'
HOMEDIR                    = path.join(__dirname,'..')
LIB_COV                    = path.join(HOMEDIR,'lib-cov')
LIB_DIR                    = if fs.existsSync(LIB_COV) then LIB_COV else path.join(HOMEDIR,'lib')
exports.PandocFilter       = require(path.join(LIB_DIR,'pandoc-filter'))
exports.CodeBlockProcessor = require(path.join(LIB_DIR,'code-block-processor'))
exports.StringCombiner     = require(path.join(LIB_DIR,'string-combiner'))
exports.UpCaser            = require(path.join(LIB_DIR,'up-caser'))
